import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#b02f00',
        'surface-container-high': '#eae7e7',
        'secondary-fixed-dim': '#8fd87d',
        'on-tertiary-fixed': '#221b00',
        'royal-indigo': '#3F51B5',
        'on-background': '#1c1b1b',
        'tertiary-container': '#c8a900',
        'surface-bright': '#fcf9f8',
        'on-primary-fixed': '#3b0900',
        'on-error-container': '#93000a',
        'outline': '#907067',
        'surface-container-highest': '#e5e2e1',
        'on-tertiary-container': '#4b3e00',
        'surface-container': '#f0eded',
        'primary-fixed': '#ffdbd1',
        'on-primary': '#ffffff',
        'secondary-fixed': '#aaf596',
        'surface-container-low': '#f6f3f2',
        'on-tertiary-fixed-variant': '#544600',
        'on-primary-fixed-variant': '#862200',
        'background': '#fcf9f8',
        'primary-container': '#ff5722',
        'on-tertiary': '#ffffff',
        'tertiary': '#705d00',
        'inverse-on-surface': '#f3f0ef',
        'surface-dim': '#dcd9d9',
        'on-surface': '#1c1b1b',
        'surface': '#fcf9f8',
        'tertiary-fixed': '#ffe16d',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'forest-deep': '#004D00',
        'tertiary-fixed-dim': '#e9c400',
        'secondary': '#286c1e',
        'on-secondary-fixed-variant': '#095305',
        'outline-variant': '#e4beb4',
        'parchment': '#FDFBF7',
        'secondary-container': '#a8f294',
        'on-surface-variant': '#5b4039',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'terracotta-clay': '#BF360C',
        'gold-leaf': '#FFD700',
        'error': '#ba1a1a',
        'primary-fixed-dim': '#ffb5a0',
        'surface-variant': '#e5e2e1',
        'inverse-surface': '#313030',
        'on-secondary-container': '#2c7022',
        'on-secondary-fixed': '#002200',
        'primary': '#b02f00',
        'sunset-orange': '#FF5722',
        'on-primary-container': '#541200',
        'inverse-primary': '#ffb5a0',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        'margin-desktop': '64px',
        'unit': '8px',
        'margin-mobile': '20px',
        'gutter': '24px',
        'section-gap': '80px',
      },
      fontFamily: {
        'headline-lg': ['"Playfair Display"', 'Georgia', 'serif'],
        'display-lg': ['"Playfair Display"', 'Georgia', 'serif'],
        'price-display': ['Montserrat', 'sans-serif'],
        'label-lg': ['Montserrat', 'sans-serif'],
        'body-md': ['Montserrat', 'sans-serif'],
        'headline-md': ['"Playfair Display"', 'Georgia', 'serif'],
        'headline-lg-mobile': ['"Playfair Display"', 'Georgia', 'serif'],
        'body-lg': ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['40px', { lineHeight: '48px', fontWeight: '700' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'price-display': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['28px', { lineHeight: '34px', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '38px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
      boxShadow: {
        'premium': '0 10px 30px -12px rgba(63, 81, 181, 0.12)',
        'card': '0 4px 20px -2px rgba(63, 81, 181, 0.08)',
      },
    },
  },
  plugins: [],
}

export default config
